dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
platforms:
  - name: server-1
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8501:8500/tcp
    networks:
      - name: "consul-high-availability"
  - name: server-2
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8502:8500/tcp
    networks:
      - name: "consul-high-availability"
  - name: server-3
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8503:8500/tcp
    networks:
      - name: "consul-high-availability"
provisioner:
  name: ansible
  # config_options:
  #   defaults:
  #     vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/vault.pw"
  env:
    ANSIBLE_ROLES_PATH: ../../../
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: testinfra
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
