dependency:
  name: galaxy
  enabled: true
driver:
  name: docker
platforms:
  - name: server
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    published_ports:
      - 127.0.0.1:8500:8500/tcp
    networks:
      - name: "consul-client-mode"
    groups:
      - controlplane
  - name: client
    image: ${MOLECULE_PLATFORM_IMAGE:-debian12-systemd}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: "consul-client-mode"
    groups:
      - clients
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: testinfra
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy
