- name: uninstall unofficial packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - docker-doc
      - podman-docker
    state: absent
  become: true

- name: add docker repostiory gpg key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

- name: add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: install docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
