- name: add grafana repostiory gpg key
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    state: present
  become: true

- name: add grafana apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.grafana.com stable main"
    state: present
  become: true

- name: install loki
  ansible.builtin.apt:
    name: loki
    state: present
  become: true
