- name: include debian specific tasks
  ansible.builtin.include_tasks: debian.yaml
  when: ansible_os_family | lower == "debian"

- name: include redhat specific tasks
  ansible.builtin.include_tasks: redhat.yaml
  when: ansible_os_family | lower == "redhat"

- name: render systemd service file
  template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: reload systemd

- name: render server config file
  template:
    src: server.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0644
  become: true
  when: consul_server_mode
  notify: restart service

- name: render client config file
  template:
    src: client.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: 0644
  become: true
  when: not consul_server_mode
  notify: restart service

- name: ensure service is started and enabled
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
  become: true

- name: flush handlers
  ansible.builtin.meta: flush_handlers

# lokalnie wykonac consul keygen
#  qDOPBEr+/oUVeOFQOnVypxwDaHzLrD+lvjo5vCEBbZ0=
# oraz consul tls ca create
# i ustawic zmienne !
